# Generated by Django 5.0.5 on 2024-05-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('vin', models.CharField(max_length=20, verbose_name='Vin')),
                ('carNumber', models.CharField(max_length=20, verbose_name='CarNumber')),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('photo', models.CharField(max_length=512, verbose_name='Photo')),
                ('longitude', models.CharField(max_length=240, verbose_name='Longitude')),
                ('latitude', models.CharField(max_length=240, verbose_name='Latitude')),
            ],
        ),
    ]
