# Generated by Django 5.0.5 on 2024-05-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
