# Generated by Django 5.0.5 on 2024-06-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=7, max_digits=5),
        ),
    ]
