# Generated by Django 5.0.5 on 2024-05-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0002_carsharing'),
    ]

    operations = [
    ]
